# Hostname of the machine runninggatekeeper. Note that this should be
# same as the file you create in the `hosts` directory in keykeeper.
hostname = 'virtual-machine'

# keykeeper repository configuration
[keykeeper]

# URL of the keykeeper repository, it should be of the format
# `https://api.github.com/repos/<ORGANIZATION>/<keykeeper-REPOSITORY>/contents`
base_url = 'https://api.github.com/keykeeper-template/contents'

# This should be a personal access token made by a member of organization on his/her
# behalf who can read the keykeeper repository. Go to this
# https://github.com/settings/tokens/new?description=keykeeper%20Token&scopes=repo
# to make a new token with correct scopes.
token = 'secret_token'

# Webhook APIs corresponding to various notifiers
[notifiers]

# Make an incoming hook to your Slack workspace from this
# app(https://slack.com/apps/A0F7XDUAZ-incoming-webhooks)
# and paste the hook URL here. You can customize the icon and name as you like.
slack = 'https://hooks.slack.com/services/ABCDEFGHI/ABCDEFGHI/abcdefghijklmnopqrstuvwx'
